CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
    avatar VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE team (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	logo VARCHAR(100) NOT NULL,
    member  VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE responselist (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	date VARCHAR(100) NOT NULL,
    place VARCHAR(100) NOT NULL,
	info VARCHAR(100) NOT NULL,
	appointment INT NOT NULL,
    teamA VARCHAR(100) NOT NULL,
	teamB VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_game (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_id VARCHAR(100) NOT NULL,
	game_id VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

